Models/UsuarioSistema.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSistema
    {
        public UsuarioSistema()
        {
            this.BoletaVendida = new HashSet<BoletaVendida>();
            this.ControlCajaUsuarioEntrega = new HashSet<ControlCajaUsuarioEntrega>();
            this.SillaBloqueo = new HashSet<SillaBloqueo>();
            this.ControlIngreso = new HashSet<ControlIngreso>();
            this.BoletaReservada = new HashSet<BoletaReservada>();
        }
    
        public int RowID { get; set; }
        public int RolID { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string NombreUsuario { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public Nullable<int> TeatroID { get; set; }
        public Nullable<int> RowIDCentral { get; set; }
        public string Foto_Empleado { get; set; }
        public Nullable<int> RowIDCreacion { get; set; }
        public Nullable<int> TeatroCreacion { get; set; }
    
        public virtual Teatro Teatro { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<BoletaVendida> BoletaVendida { get; set; }
        public virtual ICollection<ControlCajaUsuarioEntrega> ControlCajaUsuarioEntrega { get; set; }
        public virtual ICollection<SillaBloqueo> SillaBloqueo { get; set; }
        public virtual ICollection<ControlIngreso> ControlIngreso { get; set; }
        public virtual ICollection<BoletaReservada> BoletaReservada { get; set; }
    }
}

Controllers/UsuarioRolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinemaPOS.Models;
using CinemaPOS.Controllers;
using System.IO;

namespace CinemaPOS.Controllers
{
    public class UsuarioRolController : Controller
    {
        CinemaPOSEntities db = new CinemaPOSEntities();

        #region General
        private FormCollection DeSerialize(FormCollection formulario)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(formulario["formulario"]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }
        #endregion

        #region Usuario

       

        [CheckSessionOutAttribute]
        public ActionResult VistaUsuarioSistema()
        {
            ViewBag.Usuarios = db.UsuarioSistema.ToList();
            return View();
        }


        [CheckSessionOutAttribute]
        public ActionResult UsuarioSistema(int? RowID_UsuarioSistema)
        {
            ViewBag.Teatros = db.Teatro.Where(f=>f.Estado.Codigo == "ABIERTO").ToList();
            ViewBag.Roles = db.Rol.ToList();
            ViewBag.Pantallas = db.Menu.Where(f => f.Activo == true).ToList();
            if (RowID_UsuarioSistema != null && RowID_UsuarioSistema != 0)
            {
                RowID_UsuarioSistema = int.Parse(Request.Params["RowID_UsuarioSistema"].ToString());
                return View(db.UsuarioSistema.Where(t => t.RowID == RowID_UsuarioSistema).FirstOrDefault());

            }
            else
            {
                return View(new UsuarioSistema());
            }
        }

        [CheckSessionOutAttribute]
        public JsonResult GuardarUsuarioSistema(FormCollection formulario, int? RowID_UsuarioSistema, HttpPostedFileBase foto_empleado)
        {
            Boolean respuesta = false;

            UsuarioSistema ObjUsuarioSistema = new UsuarioSistema();
            string ruta_foto = ObjUsuarioSistema.Foto_Empleado;
            String nombreU = formulario["nombreUsuario"];


            // inserta solamente el afiche en miniatura



            if (RowID_UsuarioSistema == 0)
            {
                if (db.UsuarioSistema.Where(f => f.NombreUsuario == nombreU).Count() == 0)
                {
                    ObjUsuarioSistema = CargarUsuarioSistema(ObjUsuarioSistema, formulario);
                    if (foto_empleado != null)
                    {
                        ruta_foto = formulario["nombre"] + formulario["apellido"] + Path.GetExtension(foto_empleado.FileName);
                        foto_empleado.SaveAs(Server.MapPath("~/Repositorio_Imagenes/Fotos_Empleados/" + ruta_foto));
                        ruta_foto = "Repositorio_Imagenes/Fotos_Empleados/" + ruta_foto;
                        ObjUsuarioSistema.Foto_Empleado = ruta_foto;
                    }
                    try
                    {
                        db.UsuarioSistema.Add(ObjUsuarioSistema);
                        db.SaveChanges();
                        respuesta = true;

                    }
                    catch (Exception ex)
                    { return Json("Error " + ex.Message); }
                }
            }
            if (RowID_UsuarioSistema != 0)//Para Actualiar
            {
                ObjUsuarioSistema = db.UsuarioSistema.Where(t => t.RowID == RowID_UsuarioSistema).FirstOrDefault();
                List<UsuarioSistema> listaUsuario = db.UsuarioSistema.Where(f => f.NombreUsuario == nombreU).ToList();
                if (listaUsuario.Count() == 1 && listaUsuario.FirstOrDefault().RowID == ObjUsuarioSistema.RowID)
                {
                    ObjUsuarioSistema = CargarUsuarioSistema(ObjUsuarioSistema, formulario);
                    if (foto_empleado != null)
                    {
                        String path = "~/" + ObjUsuarioSistema.Foto_Empleado;
                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(Server.MapPath(path));
                        }
                        
                        //documento.SaveAs(Server.MapPath("~/Repositorio_Imagenes/Imagenes_Generales/" + adjunto));
                        //adjunto = "Repositorio_Imagenes/Imagenes_Generales/" + adjunto;

                        ruta_foto = formulario["nombre"] + formulario["apellido"] + Path.GetExtension(foto_empleado.FileName);
                        foto_empleado.SaveAs(Server.MapPath("~/Repositorio_Imagenes/Fotos_Empleados/" + ruta_foto));
                        ruta_foto = "Repositorio_Imagenes/Fotos_Empleados/" + ruta_foto;
                        ObjUsuarioSistema.Foto_Empleado = ruta_foto;
                    }

                    //if (foto_empleado != null)
                    //{
                    //    ObjUsuarioSistema.Foto_Empleado = ruta_foto;
                    //}
                    //else
                    //{
                    //    ObjUsuarioSistema.Foto_Empleado = ruta_foto;
                    //}

                    try
                    {
                        db.SaveChanges();
                        respuesta = true;
                    }
                    catch (Exception ex)
                    { return Json("Error " + ex.Message); }

                }

            }
            return Json(respuesta);
        }
        public UsuarioSistema CargarUsuarioSistema(UsuarioSistema ObjUsuarioSistema, FormCollection formulario)
        {
            ObjUsuarioSistema.NombreUsuario = formulario["nombreUsuario"];
            ObjUsuarioSistema.Contrasena = formulario["contrasena"];
            ObjUsuarioSistema.Nombre = formulario["nombre"];
            ObjUsuarioSistema.Apellido = formulario["apellido"];
            ObjUsuarioSistema.Correo = formulario["correo"];
            ObjUsuarioSistema.Telefono = formulario["telefono"];
            ObjUsuarioSistema.Sincronizado = false;
            ObjUsuarioSistema.RolID = int.Parse(formulario["rol"].ToString());
            if (!String.IsNullOrEmpty(formulario["teatro"] ))
            {
                ObjUsuarioSistema.TeatroID = int.Parse(formulario["teatro"].ToString());

            }
            if (formulario["activo"] == null)
            {
                ObjUsuarioSistema.Activo = false;
            }
            else
            {
                ObjUsuarioSistema.Activo = true;
            }
            if (ObjUsuarioSistema.RowID == 0)
            {
                ObjUsuarioSistema.CreadoPor = Session["usuario_creacion"].ToString();
                ObjUsuarioSistema.FechaCreacion = DateTime.Now;
            }
            else
            {
                ObjUsuarioSistema.ModificadoPor = Session["usuario_creacion"].ToString();
                ObjUsuarioSistema.FechaModificacion = DateTime.Now;
            }
            return ObjUsuarioSistema;
        }

        #endregion

        #region Roles

        [CheckSessionOutAttribute]
        public ActionResult VistaRolesSistema()
        {
            ViewBag.Roles = db.Rol.ToList();
            return View();
        }

        public String listaMenus(int rolID)
        {
            try
            {
                String menusA = "";
                List<RolMenu> lista = db.RolMenu.Where(p => p.RolID == rolID).ToList();
                for (int i = 0; i < lista.Count; i++)
                {
                    menusA = menusA + " - " + lista[i].Menu.Nombre;
                }

                return menusA;
            }
            catch (Exception e)
            {

            }
            return "";

        }

        [CheckSessionOutAttribute]
        public ActionResult RolesSistema(int? RowID_Roles)
        {
            if (RowID_Roles != null && RowID_Roles != 0)
            {
                RowID_Roles = int.Parse(Request.Params["RowID_Roles"].ToString());
                return View(db.Rol.Where(t => t.RowID == RowID_Roles).FirstOrDefault());
            }
            else
            {
                return View(new Rol());
            }
        }

        [CheckSessionOutAttribute]
        public JsonResult GuardarRolesSistema(FormCollection formulario, int RowID_RolesSistema)
        {
            String respuesta = "";
            Rol ObjRolSistema = new Rol();
            formulario = DeSerialize(formulario);
            if (RowID_RolesSistema == 0)
            {

                ObjRolSistema = CargarRolSistema(ObjRolSistema, formulario);
                try
                {
                    db.Rol.Add(ObjRolSistema);
                    db.SaveChanges();
                    RowID_RolesSistema = ObjRolSistema.RowID;
                }
                catch (Exception ex)
                { return Json("Error " + ex.Message); }
                respuesta = "Guardado Correctamente";

            }
            else if (RowID_RolesSistema != 0)//Para Actualiar
            {
                ObjRolSistema = db.Rol.Where(t => t.RowID == RowID_RolesSistema).FirstOrDefault();
                ObjRolSistema = CargarRolSistema(ObjRolSistema, formulario);
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                { return Json("Error " + ex.Message); }

Views/UsuarioRol/RolesSistema.cshtml
@model CinemaPOS.Models.Rol

@{

    ViewBag.Title = "Crear roles del sistema";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}

<script>
    function guardar_RolesSistema() {
        $.ajax({
            type: "POST",
            url: "/UsuarioRol/GuardarRolesSistema",
            data: {
                RowID_RolesSistema: $("#row_id").val(),
                formulario: $("#formulario_RolSistema").serialize(),
            },
            success: function (data) {
                $("#row_id").val(data.RolID);
                guardar_Permisos();
            },
            error: function (data) {
                swal("ERROR", data, "error");
            }
        });
    }

    function guardar_Permisos() {
        var validator = $("#formularioPermisosRol").validate();
        if (validator.form()) {
            var pantallasAsignadas = "";
            var pantallasNOAsignadas = "";
            $("#pantallas option:selected").each(function () {
                pantallasAsignadas += $(this).val() + ",";
            });
            $("#pantallas option").each(function () {
                pantallasNOAsignadas += $(this).val() + ",";
            });
            $.blockUI({ message: '<img style="width:30%; height:30%;" src="@("/Repositorio_Imagenes/Imagenes_Generales/Cargando.gif")" />' });
            $.ajax({
                type: "POST",
                url: "/UsuarioRol/GuardarPermisosRol",
                data: {
                    RolID: $("#row_id").val(),
                    pantallasAsignadas: pantallasAsignadas,
                    pantallasNOAsignadas: pantallasNOAsignadas,
                },
                success: function (data) {
                    $.unblockUI();
                    swal("OK", data, "success")
                    window.location = "/UsuarioRol/VistaRolesSistema/"
                },
                error: function (data) {
                    swal("ERROR", data, "error");
                    $.unblockUI();
                }
            });
        }
    }

    function CargarPantallasAsignadas(IdRol) {

        $("#pantallas").empty();
        $.ajax({
            type: "POST",
            url: "/UsuarioRol/CargarPantallasAsignadas",
            data: {
                IdRol: IdRol,
            },
            success: function (data) {
                $("#pantallas").empty()
                $("#pantallas").append(data).trigger("chosen:updated");
                $("#pantallas").trigger("chosen:updated");
            }
        });
    }

    $(document).ready(function () {
        $.validator.setDefaults({ ignore: ":hidden:not(select)" });
        jQuery.validator.messages.required = '*Este campo es obligatorio.';
        CargarPantallasAsignadas($("#row_id").val());
    })

</script>
<div>
    <p>
        <a class="btn btn-success" href='@Url.Action("VistaRolesSistema", "UsuarioRol")'>Vista Roles</a>
    </p>
</div>

@* formulario para agregar los datos a BD *@
<div class="panel">
    <div class="panel-heading">
        @if (Model.RowID == 0)
        {
            <h3 class="panel-title">Crear Rol</h3>
        }
        else
        {
            <h3 class="panel-title">Actualizar Rol</h3>
        }
    </div>
    <form name="formulario_RolSistema" id="formulario_RolSistema" onsubmit="return false">
        <input type="hidden" class="row_id" id="row_id" name="RowID_Rol" value="@Model.RowID" />
        <div class="panel-body">
            <div class="row">

                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="control-label">*Nombre:</label>
                        <input type="text" class="form-control" value="@Model.Nombre" name="RolNombre" required>
                    </div>
                </div>

            </div>
        </div>
    </form>

    <form name="formularioPermisosRol" id="formularioPermisosRol" onsubmit="return false">
        <div class="panel-body">

            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        <label class="control-label">Pantallas Asignadas:</label>&nbsp;<input type="button" onclick="asignar_todas()" value="Asignar todas " class="btn-success" />
                        <select multiple name="pantallas" id="pantallas" class="chosen form-control" required></select>
                    </div>
                </div>


            </div>
        </div>
    </form>
    <div class="panel-footer text-right">

        @if (Session["Usuario"] != null)
        {
            CinemaPOS.Models.UsuarioSistema user = (CinemaPOS.Models.UsuarioSistema)Session["Usuario"];
            if (user.Teatro.Nombre == CinemaPOS.ModelosPropios.Util.Constantes.NOMBRE_TEATRO_CENTRAL)
            {
                if (Model.RowID == 0)
                {
                    <input class="btn btn-success" type="submit" value="Crear Rol" onclick="guardar_RolesSistema()">
                }
                else
                {
                    <input class="btn btn-success" type="submit" value="Actualizar Rol" onclick="guardar_RolesSistema()">
                }
            }
            else
            {
                <input class="btn btn-danger add-tooltip" data-toggle="tooltip" data-original-title="Acción Denegada." value="Guardar">
            }
        }


    </div>

</div>
<script>
    function asignar_todas() {
        $("#pantallas option").each(function () {
            $(this).attr('selected', 'selected');
        });
        $("#pantallas option").trigger("chosen:updated");
    }
</script>

Views/UsuarioRol/UsuarioSistema.cshtml
@model CinemaPOS.Models.UsuarioSistema
@{
    ViewBag.Title = "Crear Usuario Sistema";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}

<script>
    function valida_formulario() {
        hasChangue = false;
        var validator = $("#formulario_UsuarioSistema").validate();
        if (validator.form()) {
            enviar_formulario();
        }
    }

    $(document).ready(function () {
        jQuery.validator.messages.required = '*Este campo es obligatorio.';
        $.validator.setDefaults({ ignore: ":hidden:not(select)" });

     });


    function enviar_formulario() {
        debugger;
        $("#formulario_UsuarioSistema").on("submit", function (e) {
            e.preventDefault();
            RowID_UsuarioSistema= $("#row_id").val();
            var f = $(this);
            var formData = new FormData(document.getElementById("formulario_UsuarioSistema"));
            //formData.append(f.attr("name"), $(this)[0].files[0]);
            $.ajax({
                url: "/UsuarioRol/GuardarUsuarioSistema?RowID_UsuarioSistema=" + RowID_UsuarioSistema,
                type: "post",
                dataType: "html",
                data:  formData, 
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    debugger;
                    if (data=="false") {
                        Alerts("El nombre de usuario, ya existe!!!", "warning");
                    } else {
                        Alerts("Usuario guardado con exito!!!", "success");
                        window.location = "/UsuarioRol/VistaUsuarioSistema/"
                    }
                },
                error: function (data) {
                    swal("ERROR", data, "warning");
                }

            })
        });
    }
</script>

<div>
    <p>
        <a class="btn btn-success" href='@Url.Action("VistaUsuarioSistema", "UsuarioRol")'>Vista Usuario</a>
    </p>
    
</div>

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Usuario</h3>
    </div>
    

        <form name="formulario_UsuarioSistema" id="formulario_UsuarioSistema"  enctype="multipart/form-data">
            <input type="hidden" class="row_id" id="row_id" name="RowID_UsuarioSistema" value="@Model.RowID" />
            <div class="panel-body">
                <div class="row">
                    
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">*Nombre:</label>
                            <input type="text" class="form-control" value="@Model.Nombre" name="nombre" required>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">*Apellido:</label>
                            <input type="text" class="form-control" value="@Model.Apellido" name="apellido" required>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">*Rol:</label>
                            <select name="rol" class="chosen form-control" required>
                                @*<option disabled selected>Seleccione una opcion</option>*@
                                @foreach (CinemaPOS.Models.Rol roles in ViewBag.Roles)
                                {
                                    if (Model.RowID != 0 && roles.RowID == Model.RolID)
                                    {
                                        <option value="@roles.RowID" selected>@roles.Nombre</option>
                                    }
                                    else
                                    {
                                        <option value="@roles.RowID">@roles.Nombre</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Teatro*:</label>
                            <select name="teatro" id="teatro" class="chosen form-control" required>
                                <option value="" disabled selected>Seleccione una opción</option>
                                @foreach (CinemaPOS.Models.Teatro item in ViewBag.Teatros)
                                {
                                    if (Model.TeatroID == item.RowID)
                                    {
                                        <option value="@item.RowID" selected>@item.Nombre - @item.Ciudad.Nombre</option>
                                    }
                                    else
                                    {
                                        <option value="@item.RowID">@item.Nombre - @item.Ciudad.Nombre</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label">*Nombre Usuario:</label>
                            <input type="text" class="form-control" value="@Model.NombreUsuario" name="nombreUsuario" required>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label">*Contraseña:</label>
                            <input type="password" class="form-control" value="@Model.Contrasena" name="contrasena" required>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label">Correo:</label>
                            <input type="email" class="form-control" value="@Model.Correo" name="correo">
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label">Telefono:</label>
                            <input type="text" class="form-control" value="@Model.Telefono" name="telefono">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="control-label">Activo:</label>
                            <div class="form-control">
                                @{string Activo = Model.Activo == true ? "checked" : ""; }
                                <input id="demo-sw-checked" type="checkbox" name="activo"  @Activo>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Foto del empleado</label>
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                    @if (Model.Foto_Empleado != null)
                                    {
                                        <img src="/@Model.Foto_Empleado" />
                                    }
                                    else
                                    {
                                        <img src="/Repositorio_Imagenes/Imagenes_Generales/thumbnail-default.png" />
                                    }

                                        
                                </div>
                                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;">
                                </div>
                                <div>
                                    <span class="btn btn-file">
                                        <span class="fileupload-new">Selecccionar imagen</span>
                                        <span class="fileupload-exists">Cambiar</span>
                                        <input type="file" accept="image/jpeg,image/png,image/gif" id="foto_empleado" onchange="ValidarImagen(this,400,400,130000)"  class="default" name="foto_empleado">
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>







                        </div>

            </div>
            <div class="panel-footer text-right">

                @if (Session["Usuario"] != null)
                {
                    CinemaPOS.Models.UsuarioSistema user = (CinemaPOS.Models.UsuarioSistema)Session["Usuario"];
                    if (user.Teatro.Nombre == CinemaPOS.ModelosPropios.Util.Constantes.NOMBRE_TEATRO_CENTRAL)
                    {
                        if (Model.RowID == 0)
                        {
                            <input class="btn btn-success" type="submit" value="Crear Usuario" onclick="javascript:valida_formulario()">
                        }
                        else
                        {
                            <input class="btn btn-success" type="submit" value="Actualizar Usuario" onclick="javascript:valida_formulario()">
                        }
                    }
                    else
                    {
                        <input class="btn btn-danger add-tooltip" data-toggle="tooltip" data-original-title="Acción Denegada." value="Guardar">
                    }
                }


            </div>
        </form>

    
</div>