Models/Pqrs.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pqrs
    {
        public Pqrs()
        {
            this.EvidenciaPqrs = new HashSet<EvidenciaPqrs>();
            this.Seguimiento = new HashSet<Seguimiento>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> TeatroID { get; set; }
        public Nullable<int> TipoSolicitudID { get; set; }
        public Nullable<int> TerceroID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaSuceso { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual ICollection<EvidenciaPqrs> EvidenciaPqrs { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
        public virtual Teatro Teatro { get; set; }
    }
}

Models/Seguimiento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public Seguimiento()
        {
            this.SeguientoEvidencia = new HashSet<SeguientoEvidencia>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> AreaAnteriorID { get; set; }
        public Nullable<int> AreaActualID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<int> PQRS_ID { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Pqrs Pqrs { get; set; }
        public virtual ICollection<SeguientoEvidencia> SeguientoEvidencia { get; set; }
    }
}

Models/TipoSolicitud.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSolicitud
    {
        public TipoSolicitud()
        {
            this.Pqrs = new HashSet<Pqrs>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Opcion Opcion { get; set; }
        public virtual ICollection<Pqrs> Pqrs { get; set; }
    }
}

Controllers/PQRSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinemaPOS.Models;
using CinemaPOS.ModelosPropios;
namespace CinemaPOS.Controllers.Inicio
{
    public class PQRSController : Controller
    {
        //
        // GET: /PQRS/
    CinemaPOSEntities db = new CinemaPOSEntities();
        private FormCollection DeSerialize(FormCollection formulario)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(formulario["formulario"]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }

        #region PQRS
        [CheckSessionOutAttribute]
        public ActionResult CreacionPQRS(int? RowID_pqrs, int? RowIdTercero)
        {

            //ViewBag.TipoTerceroID = new List<Opcion>();
            ViewBag.TipoTerceroID = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOTERCERO").ToList();
            ViewBag.SexoID = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOSEXO").ToList();
            ViewBag.CiudadID = db.Ciudad.ToList().OrderBy(f => f.Nombre);
            ViewBag.TipoIdentificacion = db.Opcion.Where(f => f.Tipo.Codigo == "TIPOIDENTIFICACION").ToList();

            if (RowID_pqrs == null || RowID_pqrs == 0)
            {

                return View(new ModelosPropios.Model.Modelos_Pqrs());
            }
            else
            {

                ModelosPropios.Model.Modelos_Pqrs ObjModelos = new ModelosPropios.Model.Modelos_Pqrs();
                ObjModelos.Pqrs_Terceros = db.Pqrs.Where(p => p.RowID == RowID_pqrs).ToList();
                ObjModelos.Pqrs_Seguimiento = db.Seguimiento.Where(p => p.PQRS_ID == RowID_pqrs).ToList();
                return View(ObjModelos);

            }
        }

        [CheckSessionOutAttribute]
        public ActionResult ModalTercero()
        {

            var TipoAreas = db.Tipo.Where(f => f.Codigo == Util.Constantes.TIPO_AREA).FirstOrDefault();
            var TipoEstados = db.TipoEstado.Where(f => f.Codigo == Util.Constantes.TIPO_ESTADO_PQRS).FirstOrDefault();
            ViewBag.Teatros = db.Teatro.ToList();
            ViewBag.TipoPQRS = db.TipoSolicitud.Where(ts => ts.Estado == true).ToList();
            ViewBag.CambioArea = db.Opcion.Where(f => f.TipoID == TipoAreas.RowID).ToList();
            ViewBag.Estados = db.Estado.Where(f => f.TipoEstadoID == TipoEstados.RowID).ToList();
            return View();
        }

        [CheckSessionOutAttribute]
        public JsonResult Guardar_PQRS(FormCollection formulario, int? RowIDTercero)
        {
            formulario = DeSerialize(formulario);
            Pqrs Obj_pqrs = new Pqrs();
            if (formulario["PQRS_Id"] != null)
            {
                if (!String.IsNullOrEmpty(formulario["PQRS_Id"].ToString()))
                {
                    int rowId = Convert.ToInt32(formulario["PQRS_Id"].ToString());
                    Obj_pqrs = db.Pqrs.FirstOrDefault(f => f.RowID == rowId);
                }
            }
            Obj_pqrs.TeatroID = int.Parse(formulario["TeatroID"]);
            Obj_pqrs.TipoSolicitudID = int.Parse(formulario["tiposolicitud"]);
            Obj_pqrs.TerceroID = RowIDTercero;
            Obj_pqrs.EstadoID = db.Estado.Where(e => e.TipoEstado.Codigo == "TIPOPQRS" && e.Nombre == "Recibida").FirstOrDefault().RowID;
            Obj_pqrs.Titulo = formulario["Titulo"];
            Obj_pqrs.Descripcion = formulario["descripcion-pqrs"];
            Obj_pqrs.FechaSuceso = Util.FechaInsertar(formulario["fecha_suceso"]);
            Obj_pqrs.FechaCreacion = DateTime.Now;
            Obj_pqrs.CreadoPor = Session["usuario_creacion"].ToString();
            if (formulario["PQRS_Id"] != null)
            {
                if (String.IsNullOrEmpty(formulario["PQRS_Id"].ToString()))
                {
                    db.Pqrs.Add(Obj_pqrs);
                }
            }
            db.SaveChanges();
            return Json(Obj_pqrs.RowID);
        }

        [CheckSessionOutAttribute]
        public JsonResult CargarCLiente()
        {
            string term = Request.Params["term"];
            try
            {
                var data = (from Sucur in db.Tercero
                                                 .Where(f => f.Nombre.Contains(term) || f.Identificacion.Contains(term.Trim())).ToList()
                            select new
                            {
                                rowid = Sucur.RowID,
                                nombre = Sucur.Nombre,
                                label = Sucur.Nombre + " " + Sucur.Apellidos


                            }).Distinct().OrderBy(f => f.label).Take(15);
                //data = data.Where(f => f.label.Contains(term));
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }

        }

        [CheckSessionOutAttribute]
        public ActionResult VistaPQRS()
        {
            return View(db.Pqrs.ToList());
        }

        [CheckSessionOutAttribute]
        public void EnviarCorreoRecepcion(Int32 PQRS_ID)
        {
            Pqrs pqrsCorreo = db.Pqrs.FirstOrDefault(f => f.RowID == PQRS_ID);
            MailSender.Enviar_RecepcionPQRS(pqrsCorreo, "PLANTILLA_RECEPCION_PQRS", Session["usuario_creacion"].ToString(), null, pqrsCorreo.Tercero.Correo, "camilop@pangea.com.co");
        }



        #endregion

        #region PQRS - Tipo Solicitud
        [CheckSessionOutAttribute]
        public ActionResult VistaTipoSolicitud()
        {
            return View(db.TipoSolicitud.ToList());
        }

        [CheckSessionOutAttribute]
        public ActionResult TipoSolicitud(int? TipoSolicitud_pqrs)
        {
            var TipoAreas = db.Tipo.Where(f => f.Codigo == Util.Constantes.TIPO_AREA).FirstOrDefault();
            ViewBag.ListaAreas = db.Opcion.Where(f => f.TipoID == TipoAreas.RowID && f.Activo == true).ToList();
            TipoSolicitud  solicitud= new TipoSolicitud();
            if (TipoSolicitud_pqrs != null)
            {
                solicitud = db.TipoSolicitud.Where(f => f.RowID == TipoSolicitud_pqrs).FirstOrDefault();
            }
           
            return View(solicitud);
        }

        

        [CheckSessionOutAttribute]
        public JsonResult guardar_TipoSolicitud(FormCollection formulario)
        {
            formulario = DeSerialize(formulario);
            String respuesta = "";
            int RowidSeguimiento = 0;
            TipoSolicitud tipoSolicitud = new TipoSolicitud();
            if (formulario["RowID_TipoSolicitud"] != null)
            {
                RowidSeguimiento = Int32.Parse(formulario["RowID_TipoSolicitud"].ToString());
                if (RowidSeguimiento !=0 )
                {
                    tipoSolicitud = db.TipoSolicitud.FirstOrDefault(f => f.RowID == RowidSeguimiento);
                }
            }
            
            try
            {
                tipoSolicitud.Nombre = formulario["nombre"];
                tipoSolicitud.AreaID = Convert.ToInt32(formulario["Area"]);
                if (formulario["activo"] == null)
                {
                    tipoSolicitud.Estado = false;
                }
                else
                {
                    tipoSolicitud.Estado = true;
                }
                tipoSolicitud.Descripcion = formulario["descripcion"];                
                if (RowidSeguimiento == 0) {
                    tipoSolicitud.FechaCreacion = DateTime.Now;
                    tipoSolicitud.CreadoPor = Session["usuario_creacion"].ToString();
                    db.TipoSolicitud.Add(tipoSolicitud);
                    respuesta = "Guardado Correctamente";
                }
                else
                {
                    respuesta = "Actualizado Correctamente";
                }               
                db.SaveChanges();
                return Json(new { respuesta = respuesta, tipoRespuesta = "success" });
            }
            catch (Exception)
            {
                return Json(new { respuesta = "Error", tipoRespuesta = "error"});
            }
        }


        #endregion

        #region Seguimiento 
        [CheckSessionOutAttribute]
        public ActionResult Seguimiento(int? Rowid_Pqrs)
        {
            var TipoAreas = db.Tipo.Where(f => f.Codigo == Util.Constantes.TIPO_AREA).FirstOrDefault();
            var TipoEstados = db.TipoEstado.Where(f => f.Codigo == Util.Constantes.TIPO_ESTADO_PQRS).FirstOrDefault();
            ViewBag.CambioArea = db.Opcion.Where(f => f.TipoID == TipoAreas.RowID && f.Activo == true).ToList();
            ViewBag.Estados = db.Estado.Where(f => f.TipoEstadoID == TipoEstados.RowID).ToList();
            return View(db.Pqrs.Where(s => s.RowID == Rowid_Pqrs).FirstOrDefault());
        }

        [CheckSessionOutAttribute]
        public JsonResult GuardarSeguimiento(FormCollection formulario)
        {
            formulario = DeSerialize(formulario);

            Seguimiento seguimiento = new Seguimiento();
            try
            {
                seguimiento.AreaAnteriorID = Convert.ToInt32(formulario["AreaAnteriorID"]);

Views/PQRS/Seguimiento.cshtml
@model  CinemaPOS.Models.Pqrs

@{
    ViewBag.Title = "Seguimiento";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}
<div>
    <p>
        <a class="btn btn-success" href="@Url.Action("VistaPQRS", "PQRS")">Vista PQRS</a>
    </p>
</div>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Información general de la PQRS</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-10">
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">Datos del cliente</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <label class="control-label text-overflow">Nombre:  @Model.Tercero.Nombre</label>
                            </div>
                            <div class="col-lg-6">
                                <label class="control-label text-overflow">Identificacion:  @Model.Tercero.Identificacion</label>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <label class="control-label text-overflow">Telefono:  @Model.Tercero.Telefono</label>
                                </div>
                                <div class="col-lg-6">
                                    <label class="control-label text-overflow">Ciudad:  @Model.Tercero.Ciudad.Nombre</label>
                                </div>

                                <div class="row">
                                    <div class="col-lg-6">
                                        <label class="control-label text-overflow">Correo:  @Model.Tercero.Correo</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="control-label">Fecha de nacimiento:  @Model.Tercero.FechaNacimiento.Value.ToString("dd/MM/yyyy")</label>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer text-right">
            @if (Session["Usuario"] != null)
            {
                CinemaPOS.Models.UsuarioSistema user = (CinemaPOS.Models.UsuarioSistema)Session["Usuario"];
                if (user.Teatro.Nombre == CinemaPOS.ModelosPropios.Util.Constantes.NOMBRE_TEATRO_CENTRAL)
                {
                    <a onclick="javascript:EnviarCorreoRecepcion()" class="btn btn-success add-tooltip" data-toggle="tooltip" id="seguimiento" data-original-title="Enviará un correo a @Model.Tercero.Correo" style="cursor:pointer">Enviar Correo de Recepcion</a>
                }
                else
                {
                    <input class="btn btn-danger add-tooltip" data-toggle="tooltip" data-original-title="Acción Denegada." value="Enviar Correo de Recepción">
                }
            }
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">Descripción de la PQRS</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <label class="control-label text-overflow">Titulo:  @Model.Titulo</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="control-label text-overflow">Teatro:  @Model.Teatro.Nombre</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <label class="control-label text-overflow">Tipo solicitud:  @Model.TipoSolicitud.Nombre</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="control-label text-overflow">Estado:  @Model.Estado.Nombre</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <label class="control-label text-overflow">Fecha creación:  @Model.FechaCreacion.Value.ToString("dd/MM/yyyy")</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="control-label text-overflow">Fecha del suceso:  @Model.FechaSuceso.Value.ToString("dd/MM/yyyy")</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <p class="control-label text-overflow">Descripción de la PQRS: <br />@Model.Descripcion</p>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Seguimientos</h3>
                </div>
                <div class="panel-body">
                    <form id="formpqrsSeg" style="margin-top:10px">
                        <input type="hidden" name="PQRS_ID" value="@Model.RowID" id="PQRS_ID" />
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="ACTUAL">*Área Actual:</label>
                                <select name="AreaActualID" id="AreaActualID" required class="form-control">
                                    <option value="" disabled selected> Seleccione una Lista de precios:</option>
                                    @foreach (var item in (List<CinemaPOS.Models.Opcion>)ViewBag.CambioArea)
                                    {
                                        <option value="@item.RowID">@item.Nombre</option>
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="AREA">*Área de traslado:</label>
                                <select name="AreaAnteriorID" id="AreaAnteriorID" required class="form-control">
                                    <option value="" disabled selected> Seleccione una Lista de precios:</option>
                                    @foreach (var item in (List<CinemaPOS.Models.Opcion>)ViewBag.CambioArea)
                                    {
                                        <option value="@item.RowID">@item.Nombre</option>
                                    }
                                </select>
                            </div>
                        </div>


                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="AREA">*Estado:</label>
                                <select name="EstadoID" id="EstadoID" required class="form-control">
                                    <option value="" disabled selected> Seleccione una Lista de precios:</option>
                                    @foreach (var item in (List<CinemaPOS.Models.Estado>)ViewBag.Estados)
                                    {
                                        <option value="@item.RowID">@item.Nombre</option>
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="OBSERVACIONES">Observaci&oacute;n:</label>
                                <textarea name="Observaciones" id="Observaciones" class="form-control"></textarea>
                            </div>
                        </div>


                    </form>
                   </div>
                <div class="panel-footer text-right">
                    @if (Session["Usuario"] != null)
                    {
                        CinemaPOS.Models.UsuarioSistema user = (CinemaPOS.Models.UsuarioSistema)Session["Usuario"];
                        if (user.Teatro.Nombre == CinemaPOS.ModelosPropios.Util.Constantes.NOMBRE_TEATRO_CENTRAL)
                        {
                            <a onclick="javascript:GuardarSeguimiento()" class="btn btn-success" id="seguimiento" style="cursor:pointer">Guardar Seguimiento</a>
                        }
                        else
                        {
                            <input class="btn btn-danger add-tooltip" data-toggle="tooltip" data-original-title="Acción Denegada." value="Guardar Seguimiento">
                        }
                    }
                </div>

                <div class="panel-body">



                    @if (Model.Seguimiento.Count() != 0)
                    {
                        <table id="demo-dt-basic" class="table table-striped table-bordered listaSeguimiento" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Área actual</th>
                                    <th>Área de traslado</th>
                                    <th>Estado</th>
                                    <th>Observación</th>
                                    <th>Creado por</th>
                                </tr>
                            </thead>
                            @foreach (CinemaPOS.Models.Seguimiento seguimiento in Model.Seguimiento.ToList())
                            {
                                <tr>
                                    <td>@seguimiento.Opcion.Nombre</td>
                                    <td>@seguimiento.Opcion1.Nombre</td>
                                    <td>@seguimiento.Estado.Nombre</td>
                                    <td>@seguimiento.Observaciones</td>
                                    <td>@seguimiento.CreadoPor</td>
                                </tr>
                            }
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function GuardarSeguimiento() {
        var validator = $("#formpqrsSeg").validate();
        if (validator.form()) {
            ModalProcesandoShow();
            $.ajax({
                type: "POST",
                url: "/PQRS/GuardarSeguimiento",
                data: {
                    formulario: $("#formpqrsSeg").serialize(),
                },
                success: function (data) {
                    if (data == "error") {
                        ModalProcesandoHiden();
                        Alerts("Error al guardar los datos.", "danger");
                    } else {
                        ModalProcesandoHiden();
                        Alerts("Datos Guardados Correctamente.", "success");
                        CargarListaSeguimiento();
                    }
                },
                error: function (request) {
                    ModalProcesandoHiden();
                    hasChangue = true;
                }
            });
        }
    }

    function EnviarCorreoRecepcion() {
        $.ajax({
            type: "POST",
            url: "/PQRS/EnviarCorreoRecepcion",
            data: {
                PQRS_ID: $("#PQRS_ID").val(),
            },
            success: function (data) {
                Alerts("Correo enviado correctamente.", "success");
            },
            error: function (request) {
            }
        });
    }

    function CargarListaSeguimiento() {
            $.ajax({
                type: "POST",
                url: "/PQRS/CargarListaSeguimiento",
                data: {
                    PQRS_ID: $("#PQRS_ID").val(),
                },
                success: function (data) {
                    jQuery(".listaSeguimiento > tbody").empty().append(data);
                },
                error: function (request) {
                }
            });
    }

    $(document).ready(function () {
        jQuery.validator.messages.required = '*Este campo es obligatorio.';
        $.validator.setDefaults({ ignore: ":hidden:not(select)" });

    });
</script>

Views/PQRS/VistaTipoSolicitud.cshtml
@model IEnumerable<CinemaPOS.Models.TipoSolicitud>

@{
    ViewBag.Title = "Vista Tipo Solicitud";
    Layout = "~/Views/Inicio/Diseño.cshtml";
}
<head>
    <!--jQuery [ REQUIRED ]-->
    <script src="~/Content/js/jquery-2.2.4.min.js"></script>
    <!--DataTables [ OPTIONAL ]-->
    <script src="~/Content/plugins/datatables/media/js/jquery.dataTables.js"></script>
    <script src="~/Content/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
    <script src="~/Content/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
    <!--DataTables Sample [ SAMPLE ]-->
    <script src="~/Content/js/demo/tables-datatables.js"></script>
</head>

<p>
    <a class="btn btn-success" href='@Url.Action("TipoSolicitud", "PQRS")'>Nuevo Tipo Solicitud</a>
</p>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Lista PQRS - Tipo Solicitud </h3>
    </div>
    <div class="panel-body">
        <table id="demo-dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Área</th>
                    <th>Activo</th>
                    <th>Descripción</th>
                    <th>Fecha creación</th>
                    <th>Creado por</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (CinemaPOS.Models.TipoSolicitud item in Model.ToList())
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>
                            @if (item.Opcion != null)
                            {
                                @item.Opcion.Nombre
                            }
                        </td>
                        @if (item.Estado == true)
                        {
                            <td>SI</td>
                        }
                        else
                        {
                            <td>NO</td>

                        }
                        <td>@item.Descripcion</td>
                        <td>@item.FechaCreacion.ToString("dd/MM/yyyy")</td>
                        <td>@item.CreadoPor</td>
                        <td><a href="@Url.Action("TipoSolicitud", "PQRS", new { TipoSolicitud_pqrs = item.RowID })"><i class="glyphicon glyphicon-pencil"></i></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>